name: compile CPU code

on: [push]

jobs:
  build:
    strategy:
      matrix:
        image: ["docker.io/centos7", "docker.io/ubuntu:18.04", "docker.io/ubuntu:20.04", "docker.io/ubuntu:22.04"]
    runs-on: ubuntu-20.04
    container: ${{ matrix.image  }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        git submodule init
        git submodule update
    - name: make (without CUDA support)
      run: make graph_viewer CUDA_SUPPORT=0
      working-directory: ./builds/linux
