name: compile CPU code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: pull submodules
      run: git submodule init && git submodule update
    - name: make (without CUDA support)
      run: cd builds/linux && make graph_viewer CUDA_SUPPORT=0
