name: compile CPU code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: make (without CUDA support)
      run: make graph_viewer CUDA_SUPPORT=0
      working-directory: ./builds/linux
