name: "Validate CITATION.cff"

on:
  push:
    paths:
      - "CITATION.cff"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Run validation"
        uses: "citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084"
        with:
          args: "--validate"
